language: nix

services:
- docker

jobs:
  include:
    - name: "Run tests"
      env: SERVICE=tests
    - name: "Build native on Arch Linux"
      env: SERVICE=build-archlinux
    - name: "Build native on NixOS"
      env: SERVICE=build-nixos
    - name: "Build native on Ubuntu"
      env: SERVICE=build-ubuntu

script: docker-compose run $SERVICE
