language: nix

services:
- docker

jobs:
  include:
    - name: "Build native libs on Arch Linux"
      env: SERVICE=build-archlinux
    - name: "Build native libs on NixOS"
      env: SERVICE=build-nixos
    - name: "Build native libs on Ubuntu"
      env: SERVICE=build-ubuntu

script: docker-compose run $SERVICE
