version: "3.3"
services:
  tests:
    image: barichello/godot-ci:3.2.2
    environment:
      - RUN_FULL_CODEPOINT_TESTS=true
    volumes:
      - .:/src
    command: godot --path /src -s addons/gut/gut_cmdln.gd
  build-archlinux:
    build:
      context: .
      dockerfile: ./dockerfiles/archlinux
    command: bash /src/addons/godot_xterm_native/build.sh
  build-nixos:
    build:
      context: .
      dockerfile: ./dockerfiles/nixos
    command: /src/addons/godot_xterm_native/build.sh
  build-ubuntu:
    build:
      context: .
      dockerfile: ./dockerfiles/ubuntu
    command: bash /src/addons/godot_xterm_native/build.sh
