version: "3.3"
services:
  build-archlinux:
    build:
      context: .
      dockerfile: ./dockerfiles/archlinux
    command: bash /src/addons/godot_xterm/native/build.sh
  build-nixos:
    build:
      context: .
      dockerfile: ./dockerfiles/nixos
    command: /src/addons/godot_xterm/native/build.sh
  build-ubuntu:
    build:
      context: .
      dockerfile: ./dockerfiles/ubuntu
    command: bash /src/addons/godot_xterm/native/build.sh
